apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gridos.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gridos.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
